POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "thanh123",
    "password": "thanh"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "thanh",
    "password": "thanh"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmEyMjZkN2VmMTU0NmQwODUzN2Q5ZTMiLCJpYXQiOjE2NTQ4NDEyOTN9.y9dRw0LS6QmkKAaqGPOOZlaJ9OTKY8kTVYZut2pdQ8c

{ 
    "title": "this javaerte post",
    "description": "java aaaaqefwetwq",
    "url": "java.com",
    "status": "LEARNED"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmEyMjZkN2VmMTU0NmQwODUzN2Q5ZTMiLCJpYXQiOjE2NTQ4NDEyOTN9.y9dRw0LS6QmkKAaqGPOOZlaJ9OTKY8kTVYZut2pdQ8c

###
PUT http://localhost:5000/api/posts/62a2e2fce39fe84df4c4df29
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmEyMjZkN2VmMTU0NmQwODUzN2Q5ZTMiLCJpYXQiOjE2NTQ4NDEyOTN9.y9dRw0LS6QmkKAaqGPOOZlaJ9OTKY8kTVYZut2pdQ8c

{ 
    "title": "javascript",
    "description": "jsxqw",
    "url": "reactjs.org",
    "status": "LEARNED"
}

###
DELETE http://localhost:5000/api/posts/62a2e2fce39fe84df4c4df29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmEyMjZkN2VmMTU0NmQwODUzN2Q5ZTMiLCJpYXQiOjE2NTQ4NDEyOTN9.y9dRw0LS6QmkKAaqGPOOZlaJ9OTKY8kTVYZut2pdQ8c
